version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8002:80"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-tasks}
            - DB_USERNAME=${DB_USERNAME:-laravel_user}
            - DB_PASSWORD=${DB_PASSWORD:-password}
        networks:
            - app-network
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: on-failure
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-tasks}
            - MYSQL_USER=${DB_USERNAME:-laravel_user}
            - MYSQL_PASSWORD=${DB_PASSWORD:-password}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
        command: --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --max_allowed_packet=128M
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
